### ISSUE TITLE
stumpy 1.12 is not compatible with 1.11

### ISSUE THREAD

**Issue by parfeniukink** [TDAmeritrade/stumpy#914]
I found that after update to 1.12 the `P_` is not working anymore.

Here is the code snippet:
```python
def foo():
    baseline: aampi = pickle.loads(filename)
    print(baseline.P_)
```
```bash
"foo.py", line 3, in foo
    print(baseline.P_)
             ^^^^^^^^^
  File "/venv_path/lib/python3.11/site-packages/stumpy/aampi.py", line 365, in P_
    if self._k == 1:
       ^^^^^^^
AttributeError: 'aampi' object has no attribute '_k'
```

**Comment by seanlaw** [comment]
@parfeniukink Thank you for your question. It's hard to tell without more information/code but I think this is an issue with pickling and less so an issue with `stumpy`. It appears that you are trying to unpickle a STUMPY 1.12 object within a STUMPY 1.11 environment. Is that correct? 

Can you provide a small end-to-end reproducible code example that produces the issue?

**Comment by parfeniukink** [comment]
@seanlaw Good question! Let me doublecheck it :)

_P.S. Thanks for the quick response!_

**Comment by seanlaw** [comment]
@parfeniukink Any updates on this?

**Comment by parfeniukink** [comment]
> @parfeniukink Any updates on this?

Hey! Yeah, thanks for waiting! Works even without the `baseline._k = 1`
We can close that one.
